### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by fortunto2** [fperazzi/davis#1]
Hi,  i try to run

```
~/davis/python/experiments$ python ./eval_simple.py
Traceback (most recent call last):
  File "./eval_simple.py", line 21, in <module>
    from davis         import cfg,log,Timer
  File "/home/rustam/davis/python/lib/davis/__init__.py", line 13, in <module>
    from dataset.loader import DAVISAnnotationLoader,DAVISSegmentationLoader
  File "/home/rustam/davis/python/lib/davis/dataset/__init__.py", line 9, in <module>
    from loader import DAVISAnnotationLoader,DAVISSegmentationLoader
  File "/home/rustam/davis/python/lib/davis/dataset/loader.py", line 40, in <module>
    from davis.measures import db_eval_boundary,db_eval_iou,db_eval_t_stab
  File "/home/rustam/davis/python/lib/davis/measures/__init__.py", line 3, in <module>
    from t_stability import db_eval_t_stab
  File "/home/rustam/davis/python/lib/davis/measures/t_stability.py", line 6, in <module>
    from tstab import *
ImportError: No module named tstab

```

**tstab** need to make from source?
https://github.com/fperazzi/davis/blob/b5b4d4c93c489119e8d121c63bf179cb78111736/CMakeLists.txt

```
# Create python library
add_library(tstab SHARED cpp/polycont/python.cpp cpp/clipper/clipper.cpp)

target_link_libraries( tstab boost_numpy ${Boost_LIBRARIES} ${PYTHON_LIBRARIES} )
set_target_properties( tstab PROPERTIES PREFIX "")
```
ubuntu 16 (local desktop)
anaconda python 2.7

**Comment by fortunto2** [comment]
sorry, i see... need 
```
C++

    ./configure.sh && make -C build/release
```
I thought that this was an option

**Comment by fortunto2** [comment]
new problem ;-)

```
rustam@rustam-SSD:~/davis/python/experiments$ python eval_simple.py 
Traceback (most recent call last):
  File "eval_simple.py", line 34, in <module>
    cfg,osp.basename(sourcedir),osp.dirname(sourcedir))
  File "/home/rustam/davis/python/lib/davis/dataset/loader.py", line 103, in __init__
    assert masks_frames[0] == 0 or masks_frames[0] == 1 and \
IndexError: list index out of range
rustam@rustam-SSD:~/davis/python/experiments$ python eval_all.py 
[INFO][06-08-2016 20:35:46] Reading available techniques and results from: db_benchmark.yml
Traceback (most recent call last):
  File "eval_all.py", line 72, in <module>
    db_techniques = db_read_techniques()
  File "/home/rustam/davis/python/lib/davis/dataset/utils.py", line 165, in db_read_techniques
    return db_read_benchmark().techniques
AttributeError: 'EasyDict' object has no attribute 'techniques'
```

for this problem
```
python ./eval_train_test.py 
Traceback (most recent call last):
  File "./eval_train_test.py", line 52, in <module>
    db_techniques = db_read_techniques()
  File "/home/rustam/davis/python/lib/davis/dataset/utils.py", line 165, in db_read_techniques
    return db_read_benchmark().techniques
  File "/home/rustam/davis/python/lib/davis/dataset/utils.py", line 152, in db_read_benchmark
    with open(cfg.FILES.DB_BENCHMARK,'r') as f:
IOError: [Errno 2] No such file or directory: '/home/rustam/davis/data/DAVIS/Results/Evaluation/db_benchmark.yml'
```
i manual create empty file  db_benchmark.yml

**Comment by fperazzi** [comment]
Hi, did you download the benchmark results? The db_benchmark.yml file is located in $DAVIS_ROOT/data/DAVIS/Results/Evaluation

**Comment by fortunto2** [comment]
yes, my mistake... sorry
but now
```
rustam@rustam-SSD:~/davis/python/experiments$ python ./eval_sequences.py 
Traceback (most recent call last):
  File "./eval_sequences.py", line 26, in <module>
    from davis import cfg,log
ImportError: No module named davis

```

**Comment by fperazzi** [comment]
export PYTHONPATH=$DAVIS_ROOT/python/lib

**Comment by fperazzi** [comment]
davis module it's not visible. You need to add it to the python path.

**Comment by fortunto2** [comment]
thanks, work

**Comment by fperazzi** [comment]
Great!

**Comment by aftikandri94** [comment]
i've tried to import all modules but it said 'no module name tstab' how do i load this module ? thanks

**Comment by fperazzi** [comment]
Did you compile the library as described in the README?

**Comment by aftikandri94** [comment]
not yet.. and how do i install this ?
1. ./configure.sh && make -C build/release

**Comment by aftikandri94** [comment]
may i have your email sir ?
